USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE IF NOT EXISTS albums (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist VARCHAR(1000) NOT NULL,
  name VARCHAR(1000) NOT NULL,
  release_date INT NOT NULL,
  sales DOUBLE NOT NULL,
  genre VARCHAR(1000) NOT NULL,
  PRIMARY KEY (id)
);